# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 432dd03aa7e5a93e8fdf6b9f48ad56d39003762c254375f89428b6cb2ce7ff1cb25bdbbc02f672036e429c1386d3e34638ef2edf3dcb9f705674a880ee52ff17

test:
  secret_key_base: 961798725e86c7f4d3a35872834eb53953250c54f7292737646184b83ce811485b1491a2a368ed4f78a0a37d9ad720d91c922cb061747aae56df6d46f8f31959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
